### ISSUE TITLE
How to deal with fork?

### ISSUE THREAD

**Issue by HugoHeneault** [LastxTemplar/curl_logger_dio_interceptor_maintained#1]
Hey @LastxTemplar :)

Thank you for the dio update and some tweaks to our original https://github.com/OwnWeb/curl_logger_dio_interceptor.

As I'm making update/fixes on it, is it worth to have both these repo maintained?

Also I would have liked to know that you were making update on our work and also using it without referencing where it came from. 

Have a nice day ;)

**Comment by LastxTemplar** [comment]
Hey @HugoHeneault , I would still like to maintain as I would like to add more features in the future. 
You mean you would like me to somehow make this repo standalone so it doesn't reference your repo at all?

**Comment by HugoHeneault** [comment]
What I meant was : is it worth to have both repo doing the same thing, requiring maintenance, based on the same code. And probably needing the same new features.

**Comment by LastxTemplar** [comment]
I have detached the repo from the fork.
As a big picture, probably not worth having such similar libraries, but i want to keep it anyway, it's my first pub.dev package and i have some ideas i would like to implement at some point.
